### ISSUE TITLE
stringInt and stringFloat

### ISSUE THREAD

**Issue by paparga** [elm-community/json-extra#10]
Hi, 
Facebook API returns numbers as strings. 
example:
`
 {  "spend": "2854.94",
    "actions": [
          {
            "action_type": "comment",
            "value": "5786"
          }
         ]
}          
` 
I could add this functions (maybe with better names), what do you think?

**Comment by lukewestby** [comment]
Sounds good to me. Can you name them `parseInt` and `parseFloat` in your PR?

**Comment by zwilias** [comment]
Merged, thanks @paparga!
