### ISSUE TITLE
The documentation for (|:) is too long

### ISSUE THREAD

**Issue by crazymykl** [elm-community/json-extra#2]
This makes tooling such as autocomplete very cumbersome. Maybe reduce it to a paragraph and have the explanation in a linked blog post or gist?

**Comment by lukewestby** [comment]
That's a good point, I'm always super annoyed when my autocomplete boxes cover the whole screen. I like the idea of having separate page for long-form documentation. I think the plan will be to have a separate markdown file in this repo that doc comments can link to. That change will happen with the release for Elm 0.18, which should be very soon.

Thanks!
