### ISSUE TITLE
:= infix for field

### ISSUE THREAD

**Issue by toastal** [elm-community/json-extra#6]
The old `Json.Decode.value` and its brother `:=` were banished… perhaps `Json.Decode.Extra` could be `:=`'s new home.

**Comment by lukewestby** [comment]
Hey! So `Json.Decode.value` is still present in `Json.Decode`. Did you mean something different?

Also, I don't know how I feel about including something like `(:=)` when it was explicitly removed from `Json.Decode` for being confusing. If more people ask for it I'll include it but for now I'd recommend just recreating it in your projects using `Json.Decode.field`
